/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostNewRouteImport } from './routes/host.new'
import { Route as HSlugRouteImport } from './routes/h.$slug'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EventsIdCheckinRouteImport } from './routes/events.$id.checkin'
import { Route as DashboardEventsNewRouteImport } from './routes/dashboard.events.new'
import { Route as DashboardEventsIdEditRouteImport } from './routes/dashboard.events.$id.edit'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostNewRoute = HostNewRouteImport.update({
  id: '/host/new',
  path: '/host/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HSlugRoute = HSlugRouteImport.update({
  id: '/h/$slug',
  path: '/h/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdCheckinRoute = EventsIdCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => EventsIdRoute,
} as any)
const DashboardEventsNewRoute = DashboardEventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsIdEditRoute = DashboardEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/h/$slug': typeof HSlugRoute
  '/host/new': typeof HostNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-events': typeof MyEventsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/h/$slug': typeof HSlugRoute
  '/host/new': typeof HostNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/my-events': typeof MyEventsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRouteWithChildren
  '/h/$slug': typeof HSlugRoute
  '/host/new': typeof HostNewRoute
  '/invite/$token': typeof InviteTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/events/new': typeof DashboardEventsNewRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/dashboard/events/$id/edit': typeof DashboardEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/my-events'
    | '/signin'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/h/$slug'
    | '/host/new'
    | '/invite/$token'
    | '/dashboard/'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/dashboard/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/my-events'
    | '/signin'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/h/$slug'
    | '/host/new'
    | '/invite/$token'
    | '/dashboard'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/dashboard/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/my-events'
    | '/signin'
    | '/signup'
    | '/tickets'
    | '/events/$id'
    | '/h/$slug'
    | '/host/new'
    | '/invite/$token'
    | '/dashboard/'
    | '/dashboard/events/new'
    | '/events/$id/checkin'
    | '/dashboard/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  MyEventsRoute: typeof MyEventsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TicketsRoute: typeof TicketsRoute
  EventsIdRoute: typeof EventsIdRouteWithChildren
  HSlugRoute: typeof HSlugRoute
  HostNewRoute: typeof HostNewRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host/new': {
      id: '/host/new'
      path: '/host/new'
      fullPath: '/host/new'
      preLoaderRoute: typeof HostNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h/$slug': {
      id: '/h/$slug'
      path: '/h/$slug'
      fullPath: '/h/$slug'
      preLoaderRoute: typeof HSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id/checkin': {
      id: '/events/$id/checkin'
      path: '/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof EventsIdCheckinRouteImport
      parentRoute: typeof EventsIdRoute
    }
    '/dashboard/events/new': {
      id: '/dashboard/events/new'
      path: '/events/new'
      fullPath: '/dashboard/events/new'
      preLoaderRoute: typeof DashboardEventsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events/$id/edit': {
      id: '/dashboard/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/dashboard/events/$id/edit'
      preLoaderRoute: typeof DashboardEventsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardEventsNewRoute: typeof DashboardEventsNewRoute
  DashboardEventsIdEditRoute: typeof DashboardEventsIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardEventsNewRoute: DashboardEventsNewRoute,
  DashboardEventsIdEditRoute: DashboardEventsIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsIdRouteChildren {
  EventsIdCheckinRoute: typeof EventsIdCheckinRoute
}

const EventsIdRouteChildren: EventsIdRouteChildren = {
  EventsIdCheckinRoute: EventsIdCheckinRoute,
}

const EventsIdRouteWithChildren = EventsIdRoute._addFileChildren(
  EventsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  MyEventsRoute: MyEventsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TicketsRoute: TicketsRoute,
  EventsIdRoute: EventsIdRouteWithChildren,
  HSlugRoute: HSlugRoute,
  HostNewRoute: HostNewRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
